let {app}=require("electron")
app.commandLine.appendSwitch("no-first-run")
app.commandLine.appendSwitch("disable-background-networking")
app.commandLine.appendSwitch("disable-component-update")
app.commandLine.appendSwitch("disable-sync")
app.commandLine.appendSwitch("disable-default-apps")
app.commandLine.appendSwitch("metrics-recording-only")
app.commandLine.appendSwitch("disable-features", "TranslateUI")
app.commandLine.appendSwitch("ignore-gpu-blacklist")
require("./main")